### ISSUE TITLE
Вопрос по RecyclerView.

### ISSUE THREAD

**Issue by Maksim933** [romychab/element-adapter#2]
Добрый день! А вы только на Kotlin программирует или на Java тоже?
Посмотрел Ваше видео "Обработка событий в ListAdapter для RecyclerView" (но это Kotlin).
Просто у меня есть вопрос по RecyclerView только на ЯП Java. Не получается реализовать правильно код. Я новичок.

**Comment by romychab** [comment]
> Добрый день! А вы только на Kotlin программирует или на Java тоже? Посмотрел Ваше видео "Обработка событий в ListAdapter для RecyclerView" (но это Kotlin). Просто у меня есть вопрос по RecyclerView только на ЯП Java. Не получается реализовать правильно код. Я новичок.

@Maksim933 Приветствую! То, что в видео "Обработка событий в ListAdapter для RecyclerView" можно и на языке Java написать. А эта библиотека - да, предназначена для языка Kotlin.

**Comment by Maksim933** [comment]
Спасибо! Я имел ввиду, что у меня не получается правильно написать код на Java обработчик событий RecyclerView
